spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    queue:
      name: sample.queue
    exchange:
      name: sample.exchange
    routing:
      key: sample.key
